//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroPolicial.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAO_Actividad
    {
        public int IdActividad { get; set; }
        public Nullable<int> IdMeta { get; set; }
        public Nullable<int> IdAvance { get; set; }
        public string Actividad { get; set; }
        public string DetalleActividad { get; set; }
    
        public virtual PAO_Avance PAO_Avance { get; set; }
        public virtual PAO_Meta PAO_Meta { get; set; }
    }
}
