//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroPolicial.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAO_Coordinacion
    {
        public int IdCoordinacion { get; set; }
        public Nullable<int> IdObjetivo { get; set; }
        public string TipoOficina { get; set; }
        public string NombreOficina { get; set; }
    
        public virtual PAO_Objetivo PAO_Objetivo { get; set; }
    }
}
