//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroPolicial.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAO_Meta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PAO_Meta()
        {
            this.PAO_Actividad = new HashSet<PAO_Actividad>();
        }
    
        public int IdMeta { get; set; }
        public Nullable<int> IdObjetivo { get; set; }
        public string FechaEI { get; set; }
        public string FechaEF { get; set; }
        public Nullable<int> ValorInicial { get; set; }
        public Nullable<int> ValorEsperado { get; set; }
        public Nullable<int> Indicador { get; set; }
        public string Formula { get; set; }
        public string TipoControl { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public string Medida { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PAO_Actividad> PAO_Actividad { get; set; }
        public virtual PAO_Objetivo PAO_Objetivo { get; set; }
    }
}
