//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroPolicial.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAO_EjeTematico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PAO_EjeTematico()
        {
            this.PAO_Objetivo = new HashSet<PAO_Objetivo>();
        }
    
        public int IdEjeTematico { get; set; }
        public string EjTematico { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PAO_Objetivo> PAO_Objetivo { get; set; }
    }
}
